sudo: required

language: python
python:
  - 3.6

services:
  - docker

env:
  matrix:
    - DOCKER_ORG=climateimpactlab
      IMAGE_NAME=clawpack-image
      SOURCE_IMAGE=rhodium/worker:v0.2.5

notifications:
  email: false

install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build --build-arg SOURCE_IMAGE=rhodium/worker:v0.2.5 -t $DOCKER_ORG/$IMAGE_NAME:$TRAVIS_COMMIT .

script:
  - docker run -t $DOCKER_ORG/$IMAGE_NAME:$TRAVIS_COMMIT /usr/bin/env bash /clawpack/run_tests.sh
  - docker push "$DOCKER_ORG/$IMAGE_NAME:$TRAVIS_COMMIT"

deploy:
  - provider: script
    script: docker tag $DOCKER_ORG/$IMAGE_NAME:$TRAVIS_COMMIT $DOCKER_ORG/$IMAGE_NAME:$TRAVIS_BRANCH && docker push "$DOCKER_ORG/$IMAGE_NAME:$TRAVIS_BRANCH"
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master

  - provider: script
    script: docker tag $DOCKER_ORG/$IMAGE_NAME:$TRAVIS_COMMIT $DOCKER_ORG/$IMAGE_NAME:latest && docker push "$DOCKER_ORG/$IMAGE_NAME:latest"
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: docker tag $DOCKER_ORG/$IMAGE_NAME:$TRAVIS_COMMIT $DOCKER_ORG/$IMAGE_NAME:$TRAVIS_TAG && docker push "$DOCKER_ORG/$IMAGE_NAME:$TRAVIS_TAG"
    skip_cleanup: true
    on:
      tags: true
