language: python
python:
  - 3.6.10
before_install:
  # Print NumPy version that is already installed by Travis CI:
  - python -c "import numpy; print(numpy.__version__)"
  - sudo apt-get update -qq
  - sudo apt-get install gfortran liblapack-pic liblapack-dev
  - pip install matplotlib
  - pip install yolk3k
  - pip install netCDF4
  - pip install xarray
  - pip install scipy
  
install:
  - pip install -e .
  - export CLAW=${PWD}
  - export FC=gfortran
  
before_script:
  - cat /proc/cpuinfo
  - gfortran -v
  - echo "DEBUGGING --------------------"
  - echo "CLAW="$CLAW
  - echo "PYTHONPATH="$PYTHONPATH
  - yolk -l
  - echo "------------------------------"

script:
  - cd $CLAW/pyclaw/examples
  - nosetests
  - cd $CLAW/classic
  - nosetests
  - cd $CLAW/amrclaw
  - nosetests
  - cd $CLAW/geoclaw
  - nosetests

after_failure:
 - for failed_test_path in *_output ; do cat $failed_test_path/run_output.txt ; cat $failed_test_path/error_output.txt ; done
  
notifications:
  email: false
