sudo: required

language: python
python:
  - 3.6

services:
  - docker

env:
  matrix:
    - DOCKER_ORG=climateimpactlab
      IMAGE_NAME=clawpack-image
      SOURCE_IMAGE=rhodium/worker:v0.3.0-alpha.1

notifications:
  email: false

install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build --build-arg SOURCE_IMAGE=$SOURCE_IMAGE -t
    $DOCKER_ORG/$IMAGE_NAME:$TRAVIS_COMMIT .

script:
  - docker run -t $DOCKER_ORG/$IMAGE_NAME:$TRAVIS_COMMIT bash
    /clawpack/run_tests.sh

deploy:
  - provider: script
    script: docker push "$DOCKER_ORG/$IMAGE_NAME:$TRAVIS_COMMIT"
    skip_cleanup: true
    on:
      all_branches: true

  - provider: script
    script: docker tag $DOCKER_ORG/$IMAGE_NAME:$TRAVIS_COMMIT
                       $DOCKER_ORG/$IMAGE_NAME:$TRAVIS_BRANCH &&
                       docker push "$DOCKER_ORG/$IMAGE_NAME:$TRAVIS_BRANCH"
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master

  - provider: script
    script: docker tag $DOCKER_ORG/$IMAGE_NAME:$TRAVIS_COMMIT
                       $DOCKER_ORG/$IMAGE_NAME:latest &&
                       docker push "$DOCKER_ORG/$IMAGE_NAME:latest"
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: docker tag $DOCKER_ORG/$IMAGE_NAME:$TRAVIS_COMMIT
                       $DOCKER_ORG/$IMAGE_NAME:$TRAVIS_TAG &&
                       docker push "$DOCKER_ORG/$IMAGE_NAME:$TRAVIS_TAG"
    skip_cleanup: true
    on:
      tags: true
